# Generated by Django 4.2 on 2025-01-23 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_winner_created_at_winner_is_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
