# Generated by Django 4.2 on 2024-09-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='short_desc',
        ),
    ]
