# Generated by Django 4.2 on 2024-07-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_user_managers_and_more'),
    ]

    operations = [
    ]
