# Generated by Django 4.2 on 2024-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20240727_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
    ]
