# Generated by Django 4.2 on 2024-09-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlist_short_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
