# Generated by Django 4.2 on 2024-09-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comments_listingid_comments_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listingid',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlist'),
            preserve_default=False,
        ),
    ]
