# Generated by Django 4.2 on 2024-10-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlist_current_bid_remove_bids_listingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
