# Generated by Django 4.2 on 2024-07-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='top_bid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
