# Generated by Django 4.2 on 2024-07-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auctionlist_top_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='top_bid',
        ),
    ]
