# Generated by Django 4.2 on 2025-01-17 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid', models.IntegerField()),
                ('last_bid_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
