# Generated by Django 4.2 on 2024-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidassistant',
            name='last_bid_time',
            field=models.DateTimeField(),
        ),
    ]
