# Generated by Django 4.2 on 2024-12-05 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_bidassistant_last_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidassistant',
            name='last_bid_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
