# Generated by Django 4.2 on 2025-01-23 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassistant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidassistant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
